# Generated by Django 3.2.2 on 2024-04-09 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anagramseries',
            options={'verbose_name_plural': 'series'},
        ),
    ]
