# Generated by Django 3.2.2 on 2024-01-25 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('width', models.IntegerField(default=12)),
                ('height', models.IntegerField(default=12)),
                ('cells', models.TextField(max_length=625)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(max_length=1024)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='crosswords.dictionaryword')),
            ],
        ),
        migrations.CreateModel(
            name='CrosswordPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('puzzle_type', models.CharField(choices=[('CSWD', 'Crossword'), ('CRGM', 'Crannagram')], default='CSWD', max_length=4)),
                ('complete', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('released', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_creator', to=settings.AUTH_USER_MODEL)),
                ('grid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='crosswords.grid')),
            ],
        ),
        migrations.CreateModel(
            name='CrosswordClue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.CharField(blank=True, max_length=1024, null=True)),
                ('clue_number', models.IntegerField(default=0)),
                ('solution', models.CharField(max_length=127)),
                ('word_lengths', models.CharField(blank=True, max_length=64, null=True)),
                ('orientation', models.CharField(choices=[('AC', 'Across'), ('DN', 'Down')], default='AC', max_length=2)),
                ('start_row', models.IntegerField(blank=True, null=True)),
                ('start_col', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clues', to=settings.AUTH_USER_MODEL)),
                ('puzzle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='crosswords.crosswordpuzzle')),
            ],
        ),
    ]
