# Generated by Django 3.2.2 on 2024-04-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosswords', '0003_auto_20240409_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswordinstance',
            name='time_taken',
            field=models.DurationField(null=True),
        ),
    ]
