# Generated by Django 3.2.2 on 2024-04-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosswords', '0004_alter_crosswordinstance_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswordpuzzle',
            name='instances_completed',
            field=models.IntegerField(default=0),
        ),
    ]
