# Generated by Django 3.2.2 on 2024-11-04 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sudoku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SudokuPuzzleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('player_uuid', models.CharField(blank=True, max_length=256, null=True)),
                ('difficulty', models.IntegerField(default=0)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sudoku.sudokupuzzle')),
            ],
        ),
    ]
