# Generated by Django 3.2.2 on 2024-11-05 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crosswords', '0006_dictionaryword_crosswords__length_153860_idx'),
        ('usage_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrosswordPuzzleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('player_uuid', models.CharField(blank=True, max_length=256, null=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crosswords.crosswordpuzzle')),
            ],
        ),
    ]
